weights: yolov5m.pt
cfg: /opt/birdcam/birdcam/yolov5/models/yolov5m.yaml
data: /opt/birdcam/birdcam/yolov5/data/nabirds.yaml
hyp: /opt/birdcam/birdcam/yolov5/data/hyps/hyp.scratch.yaml
epochs: 300
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 18
project: runs/train
name: nabirds_det_v5m_b32_e300
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/nabirds_det_v5m_b32_e300
